server:
  port: 8089
spring:
  profiles:
    active: local
  config:
    import: "configserver:http://localhost:9900"
  cloud:
    config: # Ex) `http://localhost:8088/config/test`
      name: config # config name
      profile: local # config profile
      label: pcg
management:
  endpoints:
    web:
      exposure:
        include: refresh